name: SUNNY-AND-NIMA-V1
services:
  - name: SUNNY-AND-NIMA-V1-service
    type: web
    ports:
      - 5000
    routes:
      - path: "/"
    build:
      type: docker
      dockerfile: ./Dockerfile
    regions:
      - fra
      - sin
      
